### ISSUE TITLE
Improve website repo's README to include "getting started" instructions

### ISSUE THREAD

**Issue by AbhijithGanesh** [pyrsia/pyrsia.github.io#20]
Currently the _README_ file doesnot have ample information, it'd be appropriate if we can add essential information like how to set the local hugo repository up? etc

**Comment by prince-chrismc** [comment]
With the new site we now have some generic instructions, @AbhijithGanesh can you let me know if they work for you?

**Comment by betarelease** [comment]
Closing this as we already have getting started and other instructions on the website now. Create new issues as we need.
