### ISSUE TITLE
Change install.sh to use new repo location

### ISSUE THREAD

**Issue by sbtaylor15** [pyrsia/pyrsia.github.io#34]

**Comment by sbtaylor15** [comment]
Here is the new install.sh that goes at the root of the website.

```
#!/usr/bin/env bash
apt-get update
apt-get install -y wget gnupg
wget -q -O - https://repo.pyrsia.io/repos/Release.key |  gpg --dearmor  > pyrsia.gpg
install -o root -g root -m 644 pyrsia.gpg /etc/apt/trusted.gpg.d/
echo "deb https://repo.pyrsia.io/repos/nightly focal main" >> /etc/apt/sources.list
apt-get update
apt-get install -y pyrsia
```

@prince-chrismc - let me know if you want a PR for this or if you are going to put it in place when the repo is re-initialized.

**Comment by prince-chrismc** [comment]
This URL is in a handful of spots, including the main repo and the website content

- https://github.com/pyrsia/pyrsia#install-pyrsia-and-joining-the-network
- https://pyrsia.io/docs/technology/quick-installation/#using-the-web-script

**Comment by sbtaylor15** [comment]
Closing manually
